In [8]:
import numpy as np
import pandas as pd
import nltk

In [9]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [11]:
amazon_df=pd.read_csv('amazon_product.csv')
amazon_df.head()

,id,Title,Description,Category
0,1,Swissmar Capstore Select Storage Rack for 18-...,Swissmar's capstore select 18 storage unit kee...,Home & Kitchen Kitchen & Dining Kitchen Utens...
1,2,Gemini200 Delta CV-880 Gold Crown Livery Airc...,Welcome to the exciting world of GeminiJets! O...,Toys & Games Hobbies Models & Model Kits Pre-...
2,5,Superior Threads 10501-2172 Magnifico Cream P...,"For quilting and embroidery, this product is m...","Arts, Crafts & Sewing Sewing Thread & Floss S..."
3,6,Fashion Angels Color Rox Hair Chox Kit,Experiment with the haute trend of hair chalki...,Beauty & Personal Care Hair Care Hair Colorin...
4,8,Union Creative Giant Killing Figure 05: Daisu...,From Union Creative. Turn your display shelf i...,Toys & Games › Action Figures & Statues › Sta...

In [12]:
amazon_df.drop('id',axis=1,inplace=True)
amazon_df.head()

,Title,Description,Category
0,Swissmar Capstore Select Storage Rack for 18-...,Swissmar's capstore select 18 storage unit kee...,Home & Kitchen Kitchen & Dining Kitchen Utens...
1,Gemini200 Delta CV-880 Gold Crown Livery Airc...,Welcome to the exciting world of GeminiJets! O...,Toys & Games Hobbies Models & Model Kits Pre-...
2,Superior Threads 10501-2172 Magnifico Cream P...,"For quilting and embroidery, this product is m...","Arts, Crafts & Sewing Sewing Thread & Floss S..."
3,Fashion Angels Color Rox Hair Chox Kit,Experiment with the haute trend of hair chalki...,Beauty & Personal Care Hair Care Hair Colorin...
4,Union Creative Giant Killing Figure 05: Daisu...,From Union Creative. Turn your display shelf i...,Toys & Games › Action Figures & Statues › Sta...

In [13]:
amazon_df.isnull().sum()

Title          0
Description    0
Category       0
dtype: int64

In [14]:
from nltk.stem.snowball import SnowballStemmer
stemmer=SnowballStemmer('english')
def tokenize_stem(text):
    tokens=nltk.word_tokenize(text.lower())
    stemmed=[ stemmer.stem(w) for w in tokens ]
    return" ".join(stemmed)

In [15]:
amazon_df['stemmed_tokens']=amazon_df.apply(lambda row: tokenize_stem(row['Title'] + " "+row['Description']),axis=1)

In [16]:
amazon_df.head()

,Title,Description,Category,stemmed_tokens
0,Swissmar Capstore Select Storage Rack for 18-...,Swissmar's capstore select 18 storage unit kee...,Home & Kitchen Kitchen & Dining Kitchen Utens...,swissmar capstor select storag rack for 18-pac...
1,Gemini200 Delta CV-880 Gold Crown Livery Airc...,Welcome to the exciting world of GeminiJets! O...,Toys & Games Hobbies Models & Model Kits Pre-...,gemini200 delta cv-880 gold crown liveri aircr...
2,Superior Threads 10501-2172 Magnifico Cream P...,"For quilting and embroidery, this product is m...","Arts, Crafts & Sewing Sewing Thread & Floss S...",superior thread 10501-2172 magnifico cream puf...
3,Fashion Angels Color Rox Hair Chox Kit,Experiment with the haute trend of hair chalki...,Beauty & Personal Care Hair Care Hair Colorin...,fashion angel color rox hair chox kit experi w...
4,Union Creative Giant Killing Figure 05: Daisu...,From Union Creative. Turn your display shelf i...,Toys & Games › Action Figures & Statues › Sta...,union creativ giant kill figur 05 : daisuk tsu...

In [26]:



# Download required NLTK data
nltk.download('punkt')  # Download 'punkt' instead of 'punkt_tab'
nltk.download('stopwords') # Download stop words if needed


# Apply stemming and tokenization to create the 'stemmed_tokens' column
amazon_df['stemmed_tokens'] = amazon_df.apply(lambda row: tokenize_stem(row['Title'] + " " + row['Description']), axis=1)

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer(tokenizer=tokenize_stem)

# Define function to calculate cosine similarity
def calculate_cosine_similarity(txt1, txt2):
    matrix = tfidf.fit_transform([txt1, txt2])
    return cosine_similarity(matrix)[0][1]  # Extract similarity score

# Define search function
def search_product(query):
    query_stemmed = tokenize_stem(query)
    amazon_df['similarity'] = amazon_df['stemmed_tokens'].apply(lambda x: calculate_cosine_similarity(query_stemmed, x))
    results = amazon_df.sort_values(by=['similarity'], ascending=False).head(10)
    return results[['Title', 'Description', 'similarity']]

# Perform the search
search_product('Swissmar Capstore Select Storage Rack for 18-Pack')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,Title,Description,similarity
475,Pacon Spectra Glitter Sparkling Crystals,"Change all to: Spectra Glitter, Sparkling Crys...",0.851907
463,Versio Mobile 3-Pack Screen Protector for LG ...,Clear 3 Pack Screen Protector For LG G2,0.850656
593,Qmadix QM-SPHTC6410 Screen Protector for HTC ...,"Protect your device's display from dust, scrat...",0.849806
526,"Titan Classic Spandex Dreadlock Cap, Regular",Spandex Dreadlock Cap - Regular Size. Covers M...,0.849153
177,Sargent Art 22-7099 6-Count 8-Ounce Fluoresce...,Sargent art's washable watercolor magic is uni...,0.844571
0,Swissmar Capstore Select Storage Rack for 18-...,Swissmar's capstore select 18 storage unit kee...,0.842154
147,Martha Stewart Crafts 32802 Stencil Brushes (...,Transfer patterns with ease by painting over t...,0.839358
110,Core Products Elastic Criss Cross Back Suppor...,The Elastic Crisscross Back Support helps reli...,0.837629
384,Visol Ferrara Red Cigar Case - Holds 2-3 Cigars,"Vibrant red, soft leather wraps this crushproo...",0.833515
13,BRUT After Shave Classic Fragrance 5 oz (Pack...,BRUT After Shave Classic Fragrance 5 oz (Pack ...,0.831173

In [27]:
search_product('Swissmar Capstore Select Storage Rack for 18-Pack')

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,Title,Description,similarity
475,Pacon Spectra Glitter Sparkling Crystals,"Change all to: Spectra Glitter, Sparkling Crys...",0.851907
463,Versio Mobile 3-Pack Screen Protector for LG ...,Clear 3 Pack Screen Protector For LG G2,0.850656
593,Qmadix QM-SPHTC6410 Screen Protector for HTC ...,"Protect your device's display from dust, scrat...",0.849806
526,"Titan Classic Spandex Dreadlock Cap, Regular",Spandex Dreadlock Cap - Regular Size. Covers M...,0.849153
177,Sargent Art 22-7099 6-Count 8-Ounce Fluoresce...,Sargent art's washable watercolor magic is uni...,0.844571
0,Swissmar Capstore Select Storage Rack for 18-...,Swissmar's capstore select 18 storage unit kee...,0.842154
147,Martha Stewart Crafts 32802 Stencil Brushes (...,Transfer patterns with ease by painting over t...,0.839358
110,Core Products Elastic Criss Cross Back Suppor...,The Elastic Crisscross Back Support helps reli...,0.837629
384,Visol Ferrara Red Cigar Case - Holds 2-3 Cigars,"Vibrant red, soft leather wraps this crushproo...",0.833515
13,BRUT After Shave Classic Fragrance 5 oz (Pack...,BRUT After Shave Classic Fragrance 5 oz (Pack ...,0.831173

In [18]:
amazon_df['Title'][0]

' Swissmar Capstore Select Storage Rack for 18-Pack '